DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS interests CASCADE;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS interests (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  c02 BOOLEAN NOT NULL DEFAULT FALSE,
  deforestation BOOLEAN NOT NULL DEFAULT FALSE,
  wildfires BOOLEAN NOT NULL DEFAULT FALSE,
  air_quality BOOLEAN NOT NULL DEFAULT FALSE,
  fk_user_id BIGINT REFERENCES users(id)
);